version: '3.3'

services:

  mongo:
    image: mongo
    command: mongod --port ${MONGO_PORT}
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: ${MONGO_SERVER}
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_LOGIN}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - ${MONXGOEXPRESS_PORT}:${MONXGOEXPRESS_PORT}
    depends_on:
      - mongo

  server:
    build: ./ServerApp
    restart: always
    ports:
      - ${SERVER_PORT}:80
    environment:
      DatabaseSettings__Host: ${MONGO_SERVER}
      DatabaseSettings__Port: ${MONGO_PORT}
      DatabaseSettings__Login: ${MONGO_ROOT_USER}
      DatabaseSettings__Password: ${MONGO_ROOT_PASSWORD}
      ClientSettings__ClientUrl: ${CLIENT_HOST}:${CLIENT_PORT}
    depends_on:
      - mongo
  
  client:
    build: 
      context: ./ClientApp
      args:
        REACT_APP_SERVER_URL: ${SERVER_HOST}:${SERVER_PORT}
    ports:
      - ${CLIENT_PORT}:80
    stdin_open: true
    tty: true